param([object[]]$Records)
$root = Split-Path -Parent $PSScriptRoot
$json = ConvertTo-Json -InputObject @($Records) -Depth 5 -Compress
$json = $json.Replace('<','\u003c').Replace('>','\u003e').Replace('&','\u0026')
$template = @'
<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Catálogo • Vitrine Criativa</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f6f3ee;color:#243b36;font:16px system-ui}main{max-width:1200px;margin:auto;padding:40px 24px}h1{font-size:36px;margin:8px 0}p{color:#5d6c65}header{margin-bottom:26px}.controls{display:flex;gap:12px;flex-wrap:wrap;position:sticky;top:0;background:#f6f3ee;padding:16px 0}input,select,button{font:inherit;padding:12px;border:1px solid #bbc8bf;border-radius:8px;background:white}input{flex:1;min-width:240px}button{cursor:pointer;color:#194e40}button:hover{background:#e4efe8}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(310px,1fr));gap:16px}article{background:white;border:1px solid #dce3dc;border-radius:14px;padding:22px}h2{font-size:18px;line-height:1.45;margin:12px 0}.tag{font-size:12px;text-transform:uppercase;letter-spacing:1px;color:#637669}.id{display:block;font:16px ui-monospace,monospace;user-select:all;margin:12px 0}a{color:#17614e}article footer{display:flex;gap:16px;margin-top:20px}.pending{color:#986022}.note{font-size:13px;overflow-wrap:anywhere}#status{min-height:24px}#toast{position:fixed;bottom:20px;right:20px;background:#243b36;color:white;padding:12px;border-radius:8px}#toast:empty{display:none}
</style><main><header><span class="tag">Vitrine Criativa · consulta local</span><h1>Todos os produtos, uma busca.</h1><p>Encontre por nome, ID, link, categoria ou apelido. Copie o código ou abra o anúncio.</p></header>
<div class="controls"><input id="q" aria-label="Buscar produto" placeholder="Ex.: alfazema, búzios ou cole o link"><select id="person" aria-label="Influencer"><option value="">Todas as influencers</option><option>maia</option><option>nanda</option></select><select id="filter" aria-label="Situação do ID"><option value="">Todos os cadastros</option><option value="known">Com ID</option><option value="missing">ID pendente</option><option value="duplicate">ID em mais de uma pasta</option></select></div>
<p id="status" role="status"></p><div class="grid" id="cards"></div><p class="note">IDs recuperados dos cadastros, nomes de pastas e links salvos. Não foram verificados ao vivo no TikTok. Cadastros repetidos foram preservados. Para atualizar: execute scripts/atualizar-catalogo.ps1.</p><a href="CATALOGO-PRODUTOS.csv">Baixar tabela CSV</a> · <a href="CATALOGO-PRODUTOS.md">Catálogo em texto e alertas</a><div id="toast" role="status"></div></main>
<script id="data" type="application/json">__DATA__</script><script>
const data=JSON.parse(document.querySelector('#data').textContent),q=document.querySelector('#q'),person=document.querySelector('#person'),filter=document.querySelector('#filter'),cards=document.querySelector('#cards');
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const ids=r=>r.TikTokId?r.TikTokId.split(', '):[],counts={};data.forEach(r=>ids(r).forEach(id=>counts[id]=(counts[id]||0)+1));
function el(tag,text,cls){let n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n}
function render(){const raw=q.value,match=raw.match(/\/(?:pdp|view\/product)\/(?:[^/?]+\/)?(\d{19})/),terms=norm(match?match[1]:raw).trim().split(/\s+/).filter(Boolean);const shown=data.filter(r=>{const text=norm([r.Titulo,r.Pasta,r.TikTokId,r.Categoria,...(r.Aliases||[])].join(' '));return terms.every(t=>text.includes(t))&&(!person.value||r.Personagem===person.value)&&(!filter.value||(filter.value==='known'&&ids(r).length)||(filter.value==='missing'&&!ids(r).length)||(filter.value==='duplicate'&&ids(r).some(id=>counts[id]>1)))});cards.replaceChildren();document.querySelector('#status').textContent=`${shown.length} de ${data.length} cadastros · ${data.filter(r=>ids(r).length).length} com ID · ${data.filter(r=>!ids(r).length).length} pendentes`;shown.forEach(r=>{let card=el('article','');card.append(el('span',r.Personagem+' · '+(r.Categoria||'Categoria não informada'),'tag'),el('h2',r.Titulo));if(!ids(r).length)card.append(el('p','ID ainda não localizado','pending'));ids(r).forEach(id=>{card.append(el('code',id,'id'));let btn=el('button','Copiar ID');btn.onclick=async()=>{try{await navigator.clipboard.writeText(id);document.querySelector('#toast').textContent='ID copiado';setTimeout(()=>document.querySelector('#toast').textContent='',2000)}catch{prompt('Copie o ID:',id)}};card.append(btn);let link=el('a',' Abrir TikTok');link.href='https://shop.tiktok.com/br/pdp/'+id;link.target='_blank';link.rel='noopener';card.append(link);if(counts[id]>1)card.append(el('p',`Este ID aparece em ${counts[id]} pastas.`,'pending'))});let foot=el('footer',''),a=el('a','Abrir pasta');a.href=r.CaminhoRelativo.split('/').map(encodeURIComponent).join('/')+'/';foot.append(a);card.append(foot,el('p',r.CaminhoRelativo,'note'));cards.append(card)});if(!shown.length)cards.append(el('p','Nenhum produto encontrado. Experimente menos palavras.'))}
[q,person,filter].forEach(n=>n.addEventListener('input',render));render();
</script></html>
'@
Set-Content -LiteralPath (Join-Path $root 'CATALOGO-PRODUTOS.html') -Value $template.Replace('__DATA__',$json) -Encoding utf8

